# Generated by Django 2.2.2 on 2019-10-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0002_auto_20191029_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacedataset',
            name='face_data',
            field=models.CharField(max_length=10000),
        ),
    ]
