# Generated by Django 2.2.2 on 2019-10-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0003_auto_20191029_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacedataset',
            name='face_data',
            field=models.BinaryField(),
        ),
    ]
