# Generated by Django 2.2.2 on 2019-10-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0004_auto_20191029_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacedataset',
            name='face_data',
            field=models.CharField(max_length=10000),
        ),
    ]
