# Generated by Django 2.2.2 on 2019-12-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0005_auto_20191029_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfacedataset',
            name='age',
        ),
        migrations.AlterField(
            model_name='userfacedataset',
            name='face_data',
            field=models.FileField(upload_to='media/faces'),
        ),
    ]
