# Generated by Django 2.2.2 on 2019-12-16 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0006_auto_20191216_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='userfacedataset',
            name='face_images',
            field=models.FileField(default='ddd', upload_to='media/faces'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfacedataset',
            name='face_data',
            field=models.FileField(upload_to='media/embeddings'),
        ),
        migrations.AlterField(
            model_name='userfacedataset',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fr.Gender'),
        ),
    ]
