# Generated by Django 2.2.2 on 2019-12-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0007_auto_20191216_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfacedataset',
            name='gender',
        ),
        migrations.AlterField(
            model_name='userfacedataset',
            name='face_data',
            field=models.FileField(upload_to='fr/embeddings'),
        ),
        migrations.AlterField(
            model_name='userfacedataset',
            name='face_images',
            field=models.FileField(upload_to='fr/faces'),
        ),
        migrations.AlterField(
            model_name='userfacedataset',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
